apiVersion: v1
kind: Service
metadata:
  name: k8s-jaeger-collector-service
spec:
  type: ExternalName
  externalName: jaeger-collector.infra.svc.cluster.local  # 指向 infra 命名空間中的 jaeger-collector 服務
  ports:
    - port: 4317                  # 指定你希望訪問的端口（這是 dev 命名空間中代理服務的端口）
      targetPort: 4317            # 指定要轉發到的目標端口（這是 infra 命名空間中的  jaeger-collector 服務的端口）
      protocol: TCP